name: Trigger auto deployment for container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/container-AutoDeployTrigger-02457eb5-bd2a-437d-9f15-65a1a018049a.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          acrName: ca20a92f2292acr
          acrUsername: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          containerAppName: container
          resourceGroup: DefaultResourceGroup-MXC
          containerAppEnvironment: managedEnvironment-DefaultResource-9b05
          imageToBuild: ca20a92f2292acr.azurecr.io/container:${{ github.sha }}
          targetPort: 3000
