name: Trigger auto deployment for container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/container-AutoDeployTrigger-02457eb5-bd2a-437d-9f15-65a1a018049a.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Create ACR if not exists
        run: |
          echo "Checking if ACR exists..."
          if az acr show --name agendaacr --resource-group DefaultResourceGroup-MXC >/dev/null 2>&1; then
            echo "ACR agendaacr already exists"
          else
            echo "Creating ACR agendaacr..."
            az acr create --resource-group DefaultResourceGroup-MXC --name agendaacr --sku Basic --admin-enabled true
            echo "ACR created successfully"
          fi

      - name: Verify ACR exists
        run: |
          echo "Verifying ACR exists..."
          az acr show --name agendaacr --resource-group DefaultResourceGroup-MXC
          echo "ACR verification successful"

      - name: Get ACR credentials
        id: acr-credentials
        run: |
          echo "Getting ACR credentials..."
          ACR_USERNAME=$(az acr credential show --name agendaacr --query username --output tsv)
          ACR_PASSWORD=$(az acr credential show --name agendaacr --query passwords[0].value --output tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_OUTPUT
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_OUTPUT
          echo "ACR credentials obtained successfully"

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          acrName: agendaacr
          acrUsername: ${{ steps.acr-credentials.outputs.ACR_USERNAME }}
          acrPassword: ${{ steps.acr-credentials.outputs.ACR_PASSWORD }}
          containerAppName: container
          resourceGroup: DefaultResourceGroup-MXC
          containerAppEnvironment: managedEnvironment-DefaultResource-9b05
          imageToBuild: agendaacr.azurecr.io/container:${{ github.sha }}
          targetPort: 3000
